version: '3.8'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    ports:
      - "9090:9090"
        #expose:
        #- 9090    
        #networks:
        #- hostnetwork
    volumes:     
      - ./prometheus.yml:/etc/prometheus/prometheus.yml      
      - ./prometheus-data:/prometheus
    restart: on-failure
    #command:
    #- "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
        #networks:
        #- hostnetwork
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: on-failure
    depends_on:
      - prometheus
    links:
      - "prometheus"    

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
        #networks:
        #- hostnetwork
    restart: on-failure
    depends_on:
      - prometheus
    links:
      - "prometheus"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"
        #networks:
        #- hostnetwork
    restart: on-failure
  pagespeed_exporter:
    image: foomo/pagespeed_exporter:latest
    container_name: pagespeed_exporter
    restart: on-failure
    ports:
      - "9271:9271"
